//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppUploadArquivos.localhost {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="localhost.WebServiceSoap")]
    public interface WebServiceSoap {
        
        // CODEGEN: Gerando contrato de mensagem porque o nome do elemento nomeDoArquivo no namespace http://tempuri.org/ não está marcado como nulo
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UploadArquivo", ReplyAction="*")]
        AppUploadArquivos.localhost.UploadArquivoResponse UploadArquivo(AppUploadArquivos.localhost.UploadArquivoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UploadArquivo", ReplyAction="*")]
        System.Threading.Tasks.Task<AppUploadArquivos.localhost.UploadArquivoResponse> UploadArquivoAsync(AppUploadArquivos.localhost.UploadArquivoRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UploadArquivoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UploadArquivo", Namespace="http://tempuri.org/", Order=0)]
        public AppUploadArquivos.localhost.UploadArquivoRequestBody Body;
        
        public UploadArquivoRequest() {
        }
        
        public UploadArquivoRequest(AppUploadArquivos.localhost.UploadArquivoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UploadArquivoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string nomeDoArquivo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public byte[] arquivoByte;
        
        public UploadArquivoRequestBody() {
        }
        
        public UploadArquivoRequestBody(string nomeDoArquivo, byte[] arquivoByte) {
            this.nomeDoArquivo = nomeDoArquivo;
            this.arquivoByte = arquivoByte;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UploadArquivoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UploadArquivoResponse", Namespace="http://tempuri.org/", Order=0)]
        public AppUploadArquivos.localhost.UploadArquivoResponseBody Body;
        
        public UploadArquivoResponse() {
        }
        
        public UploadArquivoResponse(AppUploadArquivos.localhost.UploadArquivoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UploadArquivoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string UploadArquivoResult;
        
        public UploadArquivoResponseBody() {
        }
        
        public UploadArquivoResponseBody(string UploadArquivoResult) {
            this.UploadArquivoResult = UploadArquivoResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServiceSoapChannel : AppUploadArquivos.localhost.WebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServiceSoapClient : System.ServiceModel.ClientBase<AppUploadArquivos.localhost.WebServiceSoap>, AppUploadArquivos.localhost.WebServiceSoap {
        
        public WebServiceSoapClient() {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AppUploadArquivos.localhost.UploadArquivoResponse AppUploadArquivos.localhost.WebServiceSoap.UploadArquivo(AppUploadArquivos.localhost.UploadArquivoRequest request) {
            return base.Channel.UploadArquivo(request);
        }
        
        public string UploadArquivo(string nomeDoArquivo, byte[] arquivoByte) {
            AppUploadArquivos.localhost.UploadArquivoRequest inValue = new AppUploadArquivos.localhost.UploadArquivoRequest();
            inValue.Body = new AppUploadArquivos.localhost.UploadArquivoRequestBody();
            inValue.Body.nomeDoArquivo = nomeDoArquivo;
            inValue.Body.arquivoByte = arquivoByte;
            AppUploadArquivos.localhost.UploadArquivoResponse retVal = ((AppUploadArquivos.localhost.WebServiceSoap)(this)).UploadArquivo(inValue);
            return retVal.Body.UploadArquivoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AppUploadArquivos.localhost.UploadArquivoResponse> AppUploadArquivos.localhost.WebServiceSoap.UploadArquivoAsync(AppUploadArquivos.localhost.UploadArquivoRequest request) {
            return base.Channel.UploadArquivoAsync(request);
        }
        
        public System.Threading.Tasks.Task<AppUploadArquivos.localhost.UploadArquivoResponse> UploadArquivoAsync(string nomeDoArquivo, byte[] arquivoByte) {
            AppUploadArquivos.localhost.UploadArquivoRequest inValue = new AppUploadArquivos.localhost.UploadArquivoRequest();
            inValue.Body = new AppUploadArquivos.localhost.UploadArquivoRequestBody();
            inValue.Body.nomeDoArquivo = nomeDoArquivo;
            inValue.Body.arquivoByte = arquivoByte;
            return ((AppUploadArquivos.localhost.WebServiceSoap)(this)).UploadArquivoAsync(inValue);
        }
    }
}
